### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jcope2013** [dylang/npm-check#110]
``` 
npm-check
/Users/joshuacope/.nvm/versions/node/v0.12.9/lib/node_modules/npm-check/lib/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/joshuacope/.nvm/versions/node/v0.12.9/lib/node_modules/npm-check/bin/cli.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Node v0.12.9
OS X 10.11.4

**Comment by jcope2013** [comment]
updating node to a newer version fixed it
