### ISSUE TITLE
ES6 is mandatory?

### ISSUE THREAD

**Issue by antoniobrandao** [dylang/npm-check#115]
~/ npm-check
/usr/local/lib/node_modules/npm-check/lib/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check/bin/cli.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by lijunle** [comment]
@antoniobrandao Which version of node are you using?

**Comment by dylang** [comment]
Hi @antoniobrandao, to simplify development I'm only supporting node 4 and newer.

**Comment by antoniobrandao** [comment]
0.12.2. Thanks, will upgrade
