### ISSUE TITLE
Fresh install fails does not check required node version 

### ISSUE THREAD

**Issue by clemsos** [dylang/npm-check#121]
SyntaxError using const in strict mode

```
╰─$ npm install -g npm-check
/home/clemsos/.nvm/versions/node/v0.12.5/bin/npm-check -> /home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/npm-check/bin/cli.js
npm WARN unmet dependency /home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/browserify-test requires browserify@'^11.1.0' but will load
npm WARN unmet dependency /home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/browserify,
npm WARN unmet dependency which is version 11.0.1
npm-check@5.0.3 /home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/npm-check
├── semver-diff@2.1.0
├── is-ci@1.0.8
├── giturl@1.0.0
├── throat@2.0.2
├── text-table@0.2.0
├── semver@5.1.0
├── node-emoji@1.2.1
├── lodash@4.7.0
├── global-modules@0.2.1 (is-windows@0.1.1, global-prefix@0.1.2)
├── path-exists@2.1.0 (pinkie-promise@2.0.0)
├── merge-options@0.0.64 (is-plain-obj@1.1.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── ora@0.2.1 (object-assign@4.0.1, cli-spinners@0.1.2, cli-cursor@1.0.2)
├── inquirer@0.12.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.3.0, figures@1.5.0, through@2.3.8, cli-width@2.1.0, rx-lite@3.1.2, run-async@0.1.0, cli-cursor@1.0.2, string-width@1.0.1, readline2@1.0.1)
├── globby@4.0.0 (arrify@1.0.1, object-assign@4.0.1, pify@2.3.0, pinkie-promise@2.0.0, array-union@1.0.1, glob@6.0.4)
├── update-notifier@0.6.3 (is-npm@1.0.0, latest-version@2.0.0, boxen@0.3.1, configstore@2.0.0)
├── execa@0.2.2 (object-assign@4.0.1, strip-eof@1.0.0, path-key@1.0.0, npm-run-path@1.0.0, cross-spawn-async@2.1.9)
├── package-json@2.3.1 (registry-url@3.0.3, rc@1.1.6, got@5.5.0)
├── meow@3.7.0 (decamelize@1.2.0, map-obj@1.0.1, trim-newlines@1.0.0, object-assign@4.0.1, minimist@1.2.0, loud-rejection@1.3.0, camelcase-keys@2.1.0, redent@1.0.0, normalize-package-data@2.3.5, read-pkg-up@1.0.1)
└── depcheck@0.6.3 (deps-regex@0.1.4, builtin-modules@1.1.1, require-package-name@2.0.1, deprecate@0.1.0, walkdir@0.0.11, minimatch@3.0.0, yargs@4.3.2, js-yaml@3.5.5, babel-traverse@6.7.4, babylon@6.7.0)
╭─clemsos@clemsos  ~ ‹› 
╰─$ npm-check
/home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/npm-check/lib/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/clemsos/.nvm/versions/node/v0.12.5/lib/node_modules/npm-check/bin/cli.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

FYI

    $ uname -a                                                                                                                                         
    Linux clemsos 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux

**Comment by clemsos** [comment]
oh should be related to node version. Could you add a npm version check and throw a warning during the install process ?

**Comment by dylang** [comment]
Thanks for the suggestion @clemsos!

**Comment by clemsos** [comment]
thanks for the great tool :) and the reactivity  !
