### ISSUE TITLE
Cannot read property 'length' of undefined when run `npm-check -u`

### ISSUE THREAD

**Issue by filod** [dylang/npm-check#138]
```
Cannot read property 'length' of undefined
   54 |    }).join('\n');
   55 |};
   56 |
   57 |function dotindex (c) {
   58 |    var m = /\.[^.]*$/.exec(c);
 > 59 |    return m ? m.index + 1 : c.length;
   60 |}
   61 |
   62 |function reduce (xs, f, init) {
   63 |    if (xs.reduce) return xs.reduce(f, init);
   64 |    var i = 0;

   at dotindex (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:59:31)
   at <anonymous> (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:11:21)
   at Array.forEach ((native))
   at forEach (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:73:31)
   at <anonymous> (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:10:9)
   at Array.reduce ((native))
   at reduce (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:63:30)
   at module.exports (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/node_modules/text-table/index.js:9:20)
   at createChoices (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/lib/out/interactive-update.js:80:29)
   at <anonymous> (/Users/filod/.nvm/versions/node/v4.1.2/lib/node_modules/npm-check/lib/out/interactive-update.js:106:51)
```

by the way, i use `npm-check` in a react-native project

**Comment by filod** [comment]
i figure out why this happen. 
i have a `react-native-code-push` package which have different version among `package.json` and `/node_modules`

reinstall package may solve your problem.
