### ISSUE TITLE
npm-check fs error

### ISSUE THREAD

**Issue by antonzy** [dylang/npm-check#162]
Used to work until project got bigger.
Now fails every time.
Using version 5.2.2

```
fs.js:330
    err = new RangeError('File size is greater than possible Buffer: ' +
             ^

Error: toString failed
    at Buffer.toString (buffer.js:379:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

**Comment by canac** [comment]
Could you provide a link to a repository where you see this issue occurring?

**Comment by antonzy** [comment]
It's a private one, so I'm afraid I cannot...

**Comment by cainvommars** [comment]
I get a smiliar issue its also quite a big repo, sadly also a private one - 
```
npm-check
⠧ Checking for unused packages. --skip-unused if you don't want this.buffer.js:377
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:377:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

**Comment by cyphix333** [comment]
Well that's rather disappointing to see this was never answered as I am getting this issue too:

```
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at new SlowBuffer (buffer.js:74:10)
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:335:20)
```
