### ISSUE TITLE
toString Failed

### ISSUE THREAD

**Issue by joelcloralt** [dylang/npm-check#173]
I started getting this error now. 

```
⠹ Checking for unused packages. --skip-unused if you don't want this.fs.js:339
function readFileAfterRead(err, bytesRead) {
                ^

Error: toString failed
    at Buffer.toString (buffer.js:382:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

I tried with `--skip-unused` but still got the same error
```
⠋ Checking npm registries for updated packages.fs.js:339
function readFileAfterRead(err, bytesRead) {
                ^

Error: toString failed
    at Buffer.toString (buffer.js:382:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

Any ideas how to get around this?

**Comment by jeoffreybakker** [comment]
Probably caused by https://github.com/nodejs/node/issues/2767
Had the same problem using node 4.5.0 and had some very large sized files in the project.
Removing the large sized files solved the issue for me.
