### ISSUE TITLE
npm-check crashes v8

### ISSUE THREAD

**Issue by Adjective-Object** [dylang/npm-check#193]
likely related to #175 
```
pedantic-travis ✚❯ nice npm-check --no-emoji . web electron        
⠏ Checking for unused packages. --skip-unused if you don't want this.buffer.js:388
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:388:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

My best guess is that `npm-check` is either causing my system to run out of memory or is overrunning v8's internal limit on string size (see [node #3175](https://github.com/nodejs/node/issues/3175))

- node: 4.3.1
- npm-check:   5.4.0
- system: `Linux nyx 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- MemTotal:        3925404 kB
- MemFree:         2898260 kB
- happens when process is nice'd as well

**Comment by Duncan00** [comment]
i got similar error as yours.
```
npm-check
⠧ Checking for unused packages. --skip-unused if you don't want this.buffer.js:382
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:382:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```
