### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by zam6ak** [dylang/npm-check#20]
I am using npm-check 3.2.10

when I run it on my project following error is thrown

```
X:\Source\myproject>npm-check
X:\sdk\npm\node_modules\npm-check\node_modules\depcheck\index.js:54
          return module.replace ? module.replace(/\/.*$/, '') : module;
                       ^
TypeError: Cannot read property 'replace' of null
    at X:\sdk\npm\node_modules\npm-check\node_modules\depcheck\index.js:54:24
    at Array.map (native)
    at EventEmitter.<anonymous> (X:\sdk\npm\node_modules\npm-check\node_modules\depcheck\index.js:53:43)
    at EventEmitter.emit (events.js:118:17)
    at fn (X:\sdk\npm\node_modules\npm-check\node_modules\depcheck\node_modules\walkdir\walkdir.js:82:19)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by dylang** [comment]
This is a problem in depcheck. Do you have code I can try to see what could be causing the problem?

**Comment by zam6ak** [comment]
All I did was to run npm-check on a sample project....
I temporarily fixed the issue by editing the above mentioned line to following
```
return (module && module.replace) ? module.replace(/\/.*$/, '') : module;
```

Not sure if it is correct, but the npm-check worked afterwards...

**Comment by dylang** [comment]
this should be fixed now, we switched from depcheck to [depcheck-es6](https://github.com/lijunle/depcheck-es6).
