### ISSUE TITLE
 Unexpected end of JSON input while parsing near '...d3a038bbee7bba865bdc7'

### ISSUE THREAD

**Issue by pravichandran15** [dylang/npm-check#337]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'dot-prop' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose npm-session b440cea1dce7a2a9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/dot-prop 20ms (from cache)
8 silly fetchPackageMetaData error for dot-prop@latest Unexpected end of JSON input while parsing near '...d3a038bbee7bba865bdc7'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 72ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...d3a038bbee7bba865bdc7'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /Users/code
13 verbose Darwin 18.2.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "dot-prop"
15 verbose node v10.15.3
16 verbose npm  v6.9.0

**Comment by pravichandran15** [comment]
npm clean cache -u resolved this issue
