### ISSUE TITLE
undefined is not a function utils.hideCursor(this.rl);

### ISSUE THREAD

**Issue by r-murphy** [dylang/npm-check#39]
I just updated and encountered this error:

```
[npm-check] TypeError: undefined is not a function
    at Prompt._run (/usr/local/lib/node_modules/npm-check/lib/prompts/alt-checkbox.js:80:9)
...
```

The issue seems to be with `utils.hideCursor(this.rl);`. 
https://github.com/dylang/npm-check/blob/master/lib/prompts/alt-checkbox.js#L80

I could not find that method in inquirer/lib/utils/readline. 

I removed that line for now and it showed the packages to be updated. Then it failed on the reverse `utils.showCursor(this.rl)`. Worked okay after removing that too.

**Comment by dmassiani** [comment]
+1

**Comment by herrkessler** [comment]
+1

**Comment by november-eleven** [comment]
:+1:

**Comment by woodb** [comment]
I believe it's related, though it's not the exact same error message, that I'm getting on node v4.1.0 with the update flag.

```
$ npm-check -u
[npm-check] TypeError: utils.hideCursor is not a function
    at Prompt._run (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/lib/prompts/alt-checkbox.js:80:9)
    at Prompt.run (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (/Users/woodb/.nvm/versions/node/v4.1.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:2112:21)
```

Configuration...
```
$ node --version
v4.1.0

$ npm --version
3.3.3

$ npm-check --version
4.0.2
```

**Comment by dylang** [comment]
Thanks everyone!

New release pushed with this and other fixes.

https://github.com/dylang/npm-check/commit/d412a27137a51f8f964bd1acf1dbff0483241bfe

**Comment by woodb** [comment]
Sweet, thanks! Update fixed my issue! :+1:
