### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by november-eleven** [dylang/npm-check#40]
I have the following error when using `npm-check -u`. However, `npm-check` work just fine.

```
[npm-check] TypeError: undefined is not a function
    at Prompt._run (/usr/lib/node_modules/npm-check/lib/prompts/alt-checkbox.js:80:9)
    at Prompt.run (/usr/lib/node_modules/npm-check/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/usr/lib/node_modules/npm-check/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/lib/node_modules/npm-check/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1604:19)
    at AnonymousObservable.__subscribe (/usr/lib/node_modules/npm-check/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2112:21)
```

Few informations : 
* **npm-check** -> 4.0.2
* **npm** -> 2.14.3
* **node** -> v0.12.7
* **os** -> ArchLinux with 4.1.2-2 kernel

**Comment by november-eleven** [comment]
Duplicate of #39. Sorry for the white noise.
