### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by LunaticMuch** [dylang/npm-check#523]
Wondering if this happens to me only... tests are failing with the current version in `master`

```
> npm-check@6.0.1 test
> npm run lint && ./bin/cli.js || echo Exit Status: $?.


> npm-check@6.0.1 lint
> xo ./lib/*.js

/Users/stefano/_GITHUB/npm-check/lib/cli.js:4
const meow = require('meow');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/stefano/_GITHUB/npm-check/node_modules/meow/index.js from /Users/stefano/_GITHUB/npm-check/lib/cli.js not supported.
Instead change the require of index.js in /Users/stefano/_GITHUB/npm-check/lib/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/stefano/_GITHUB/npm-check/lib/cli.js:4:14)
    at Object.<anonymous> (/Users/stefano/_GITHUB/npm-check/bin/cli.js:9:12) {
  code: 'ERR_REQUIRE_ESM'
}
Exit Status: 1.
```

**Comment by liujiajun1994** [comment]
同问

**Comment by likaihua** [comment]
I have the same problem.

**Comment by likaihua** [comment]
> Wondering if this happens to me only... tests are failing with the current version in `master`
> 
> ```
> > npm-check@6.0.1 test
> > npm run lint && ./bin/cli.js || echo Exit Status: $?.
> 
> 
> > npm-check@6.0.1 lint
> > xo ./lib/*.js
> 
> /Users/stefano/_GITHUB/npm-check/lib/cli.js:4
> const meow = require('meow');
>              ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/stefano/_GITHUB/npm-check/node_modules/meow/index.js from /Users/stefano/_GITHUB/npm-check/lib/cli.js not supported.
> Instead change the require of index.js in /Users/stefano/_GITHUB/npm-check/lib/cli.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/Users/stefano/_GITHUB/npm-check/lib/cli.js:4:14)
>     at Object.<anonymous> (/Users/stefano/_GITHUB/npm-check/bin/cli.js:9:12) {
>   code: 'ERR_REQUIRE_ESM'
> }
> Exit Status: 1.
> ```

Have you solved your problem ？

**Comment by LunaticMuch** [comment]
LOL I should actually triple check now...too long time has passed.
