### ISSUE TITLE
npm-check -u crashes on Windows

### ISSUE THREAD

**Issue by alexisbg** [dylang/npm-check#61]
Hi,

I am running on Windows 7, node 4.2.1 and Git Bash (mintty) 2.6.2.

npm-check -s runs fine but without colors even with -c option.

But npm-check -u crashes with the following output:
$ npm-check -u
? Choose which packages to update. (Press <space> to select)

(Move up and down to reveal more choices)[npm-check] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\lib\prompts\alt-checkbox.js:117:15)
    at Prompt._run (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\lib\prompts\alt-checkbox.js:82:8)
    at Prompt.run (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\Alexis\AppData\Roaming\npm\node_modules\npm-check\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)

Thanks for your help,

Alexis

**Comment by alexisbg** [comment]
More info here:
https://github.com/SBoudrias/Inquirer.js/issues/290

**Comment by dylang** [comment]
Hi @alexisbg I've upgraded the version of `inquirer` to the latest, can you try the newest version of `npm-check` I released today (5.x.x.) and let me know if that doesn't fix the problem? Thanks!
