### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by przemyslawpluta** [dylang/npm-check#81]
After upgrading to `4.1.3` running `npm-check` with node `v0.10.33` produces this error:

``` batch
/usr/local/lib/node_modules/npm-check/node_modules/depcheck/dist/index.js:192
  return new Promise(function (resolve) {
             ^
ReferenceError: Promise is not defined
    at checkDirectory (/usr/local/lib/node_modules/npm-check/node_modules/depcheck/dist/index.js:192:14)
    at depcheck (/usr/local/lib/node_modules/npm-check/node_modules/depcheck/dist/index.js:268:10)
    at checkUnused (/usr/local/lib/node_modules/npm-check/lib/check-unused.js:30:5)
    at npmCheck (/usr/local/lib/node_modules/npm-check/lib/index.js:28:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check/lib/cli.js:36:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by lijunle** [comment]
Sorry, node v0.10 is not supported any more. Why not upgrade to a newer version (4.x or 5.x)?

**Comment by przemyslawpluta** [comment]
@lijunle thanks.
